using Zene.Windowing.Base;

namespace Zene.Windowing
{
    public enum Keys
    {
        Unknown = -1,
        D0 = GLFW.Key0,
        D1 = GLFW.Key1,
        D2 = GLFW.Key2,
        D3 = GLFW.Key3,
        D4 = GLFW.Key4,
        D5 = GLFW.Key5,
        D6 = GLFW.Key6,
        D7 = GLFW.Key7,
        D8 = GLFW.Key8,
        D9 = GLFW.Key9,
        A = GLFW.KeyA,
        B = GLFW.KeyB,
        C = GLFW.KeyC,
        D = GLFW.KeyD,
        E = GLFW.KeyE,
        F = GLFW.KeyF,
        G = GLFW.KeyG,
        H = GLFW.KeyH,
        I = GLFW.KeyI,
        J = GLFW.KeyJ,
        K = GLFW.KeyK,
        L = GLFW.KeyL,
        M = GLFW.KeyM,
        N = GLFW.KeyN,
        O = GLFW.KeyO,
        P = GLFW.KeyP,
        Q = GLFW.KeyQ,
        R = GLFW.KeyR,
        S = GLFW.KeyS,
        T = GLFW.KeyT,
        U = GLFW.KeyU,
        V = GLFW.KeyV,
        W = GLFW.KeyW,
        X = GLFW.KeyX,
        Y = GLFW.KeyY,
        Z = GLFW.KeyZ,
        Enter = GLFW.KeyEnter,
        Tab = GLFW.KeyTab,
        Space = GLFW.KeySpace,
        BackSpace = GLFW.KeyBackspace,
        Insert = GLFW.KeyInsert,
        Delete = GLFW.KeyDelete,
        Right = GLFW.KeyRight,
        Left = GLFW.KeyLeft,
        Up = GLFW.KeyUp,
        Down = GLFW.KeyDown,
        PageUp = GLFW.KeyPageUp,
        PageDown = GLFW.KeyPageDown,
        Home = GLFW.KeyHome,
        End = GLFW.KeyEnd,
        CapsLock = GLFW.KeyCapsLock,
        Escape = GLFW.KeyEscape,
        ScrollLock = GLFW.KeyScrollLock,
        NumLock = GLFW.KeyNumLock,
        Pause = GLFW.KeyPause,
        RightControl = GLFW.KeyRightControl,
        LeftControl = GLFW.KeyLeftControl,
        RightShift = GLFW.KeyRightShift,
        LeftShift = GLFW.KeyLeftShift,
        LeftSuper = GLFW.KeyLeftSuper,
        RightSuper = GLFW.KeyRightSuper,
        LeftAlt = GLFW.KeyLeftAlt,
        RightAlt = GLFW.KeyRightAlt,
        NumPadEqual = GLFW.KeyKpEqual,
        NumPadAdd = GLFW.KeyKpAdd,
        NumPadSubtract = GLFW.KeyKpSubtract,
        NumPadMultiply = GLFW.KeyKpMultiply,
        NumPadDivide = GLFW.KeyKpDivide,
        NumPadDecimal = GLFW.KeyKpDecimal,
        NumPadEnter = GLFW.KeyKpEnter,
        NumPad0 = GLFW.KeyKp0,
        NumPad1 = GLFW.KeyKp1,
        NumPad2 = GLFW.KeyKp2,
        NumPad3 = GLFW.KeyKp3,
        NumPad4 = GLFW.KeyKp4,
        NumPad5 = GLFW.KeyKp5,
        NumPad6 = GLFW.KeyKp6,
        NumPad7 = GLFW.KeyKp7,
        NumPad8 = GLFW.KeyKp8,
        NumPad9 = GLFW.KeyKp9,
        Last = GLFW.KeyLast,
        Menu = GLFW.KeyMenu,
        PrintScreen = GLFW.KeyPrintScreen,
        F1 = GLFW.KeyF1,
        F2 = GLFW.KeyF2,
        F3 = GLFW.KeyF3,
        F4 = GLFW.KeyF4,
        F5 = GLFW.KeyF5,
        F6 = GLFW.KeyF6,
        F7 = GLFW.KeyF7,
        F8 = GLFW.KeyF8,
        F9 = GLFW.KeyF9,
        F10 = GLFW.KeyF10,
        F11 = GLFW.KeyF11,
        F12 = GLFW.KeyF12,
        F13 = GLFW.KeyF13,
        F14 = GLFW.KeyF14,
        F15 = GLFW.KeyF15,
        F16 = GLFW.KeyF16,
        F17 = GLFW.KeyF17,
        F18 = GLFW.KeyF18,
        F19 = GLFW.KeyF19,
        F20 = GLFW.KeyF20,
        F21 = GLFW.KeyF21,
        F22 = GLFW.KeyF22,
        F23 = GLFW.KeyF23,
        F24 = GLFW.KeyF24,
        F25 = GLFW.KeyF25,
        Apostrophe = 39,
        Comma = 44,
        Minus = 45,
        Period = 46,
        Slash = 47,
        Semicolon = 59,
        Equal = 61,
        OpenBracket = 91,
        CloseBracket = 93,
        Backslash = 92,
        GraveAccent = 96,
        Hashtag = 35
    }

    public enum Mods
    {
        NumLock = GLFW.ModNumLock,
        CapsLock = GLFW.ModCapsLock,
        Super = GLFW.ModSuper,
        Alt = GLFW.ModAlt,
        Control = GLFW.ModControl,
        Shift = GLFW.ModShift
    }

    public enum KeyAction
    {
        Down = GLFW.Press,
        Repeat = GLFW.Repeat,
        Up = GLFW.Release
    }

    public enum MouseButton
    {
        Left = 0,
        Right = 1,
        Middle = 2,
        Last = 7,
        M1 = Left,
        M2 = Right,
        M3 = Middle,
        M4 = 3,
        M5 = 4,
        M6 = 5,
        M7 = 6,
        M8 = Last,
        None = 8
    }

    public enum CursorMode
    {
        Normal = GLFW.CursorNormal,
        Hidden = GLFW.CursorHidden,
        Disabled = GLFW.CursorDisabled
    }
}
